
# For replicaset all the meta data field of the pod will move inside spec
apiVersion: apps/v1 #for replicaset make sure its apps/v1
kind: Deployment   #Replicaset kind 
metadata:
  name: webapp 
spec:
  minReadySeconds: 30 #number of second until when replicaSet is available
  selector: #it will manage all the pods where label matches key value pair app:webapp
    matchLabels:
      app: webapp
  replicas: 2
  template: 
    metadata:  # we dont need to gives names to the pod now
     labels:   #this label will be used to identify the pod by service
       app: webapp  #key and value (webapp) should be same as in selector of service
    
    spec:
     containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0

