
# For replicaset all the meta data field of the pod will move inside spec
apiVersion: apps/v1 #for replicaset make sure its apps/v1
kind: ReplicaSet   #Replicaset kind 
metadata:
  name: webapp 
spec:
  selector: #it will manage all the pods where label matches key value pair app:webapp
    matchLabels:
      app: webapp
  replicas: 1
  template: 
    metadata:  # we dont need to gives names to the pod now
     labels:   #this label will be used to identify the pod by service
       app: webapp  #key and value (webapp) should be same as in selector of service
    
    spec:
     containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5


---
apiVersion: v1
kind: Pod   #Pod begins with capital P
metadata:
  name: queue #throw away name
  labels:   #this label will be used to identify the pod by service
    app: queue  #key and value (webapp) should be same as in selector of service
    release: zero 
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1 
